print("Hello, World!")
print("That is Daniel Luntraś :)")
print("That is Daniel Luntraś :)")
print("That is Daniel Luntraś :)")
print("That is Daniel Luntraś :)")
print("That is Daniel Luntraś :)")
print("That is Daniel Luntraś :)")
print("That is Daniel Luntraś :)")
print("That is Daniel Luntraś :)")
print("That is Daniel Luntraś :)")
print("That is Daniel Luntraś :)")
print("Hello, World!")
print("Hello, World!")
print("That is Daniel Luntraś :)")
print("That is Daniel Luntraś :)")
print("That is Daniel Luntraś :)")
print("That is Daniel Luntraś :)")
print("That is Daniel Luntraś :)")
print("That is Daniel Luntraś :)")
print("That is Daniel Luntraś :)")
print("That is Daniel Luntraś :)")
print("That is Daniel Luntraś :)")
print("That is Daniel Luntraś :)")
print("That is Daniel Luntraś :)")
print("That is Daniel Luntraś :)")
print("Hello, World!")
print("Hello, World!")
print("Hello, World!")